/*
* generated by Xtext
*/
package net.mlanoe.language.vhdl.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import net.mlanoe.language.vhdl.xtext.services.VhdlGrammarAccess;

public class VhdlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private VhdlGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT");
	}
	
	@Override
	protected net.mlanoe.language.vhdl.xtext.parser.antlr.internal.InternalVhdlParser createParser(XtextTokenStream stream) {
		return new net.mlanoe.language.vhdl.xtext.parser.antlr.internal.InternalVhdlParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public VhdlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(VhdlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
