/*
* generated by Xtext
*/
package net.mlanoe.language.vhdl.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class VhdlAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("net/mlanoe/language/vhdl/xtext/parser/antlr/internal/InternalVhdlParser.tokens");
	}
}
