/*
 * generated by Xtext
 */
package net.mlanoe.language.vhdl.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class VhdlRuntimeModule extends net.mlanoe.language.vhdl.xtext.AbstractVhdlRuntimeModule {

}
