/*
 * generated by Xtext
 */
package net.mlanoe.language.vhdl.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractVhdlValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://mlanoe.net/language/vhdl/1.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://mlanoe.net/language/vhdl/configuration/1.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://mlanoe.net/language/vhdl/declaration/1.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://mlanoe.net/language/vhdl/statement/1.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://mlanoe.net/language/vhdl/type/1.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://mlanoe.net/language/vhdl/nature/1.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://mlanoe.net/language/vhdl/expression/1.0"));
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://mlanoe.net/language/vhdl/ams/1.0"));
		return result;
	}
}
