/**
 *
 * $Id$
 */
package net.mlanoe.language.vhdl.configuration.validation;

import net.mlanoe.language.vhdl.configuration.Configuration;

/**
 * A sample validator interface for {@link net.mlanoe.language.vhdl.configuration.ConfigurationResolvedReference}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConfigurationResolvedReferenceValidator {
	boolean validate();

	boolean validateConfiguration(Configuration value);
}
