/**
 *
 * $Id$
 */
package net.mlanoe.language.vhdl.declaration.validation;

import net.mlanoe.language.vhdl.declaration.Purity;

import net.mlanoe.language.vhdl.expression.Expression;
import net.mlanoe.language.vhdl.type.TypeReference;

/**
 * A sample validator interface for {@link net.mlanoe.language.vhdl.declaration.FunctionDeclaration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FunctionDeclarationValidator {
	boolean validate();

	boolean validatePurity(Purity value);
	boolean validateReturn(TypeReference value);

	boolean validateReturn(Expression value);
}
