/**
 *
 * $Id$
 */
package net.mlanoe.language.vhdl.declaration.validation;

import net.mlanoe.language.vhdl.declaration.Declaration;
import net.mlanoe.language.vhdl.declaration.SubprogramBody;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link net.mlanoe.language.vhdl.declaration.SubprogramDeclaration}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SubprogramDeclarationValidator {
	boolean validate();

	boolean validateParameter(EList<Declaration> value);
	boolean validateBody(SubprogramBody value);
}
