/*
 * generated by Xtext
 */
package net.mlanoe.language.vhdl.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class VhdlUiModule extends net.mlanoe.language.vhdl.xtext.ui.AbstractVhdlUiModule {
	public VhdlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
