/**
 *
 * $Id$
 */
package net.mlanoe.language.vhdl.type.validation;

import net.mlanoe.language.vhdl.Name;

/**
 * A sample validator interface for {@link net.mlanoe.language.vhdl.type.PhysicalTypeDefinitionSecondary}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PhysicalTypeDefinitionSecondaryValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateNumber(String value);
	boolean validateOf(Name value);
}
