/**
 *
 * $Id$
 */
package net.mlanoe.language.vhdl.statement.validation;

import net.mlanoe.language.vhdl.GenericMaps;
import net.mlanoe.language.vhdl.Generics;
import net.mlanoe.language.vhdl.PortMaps;
import net.mlanoe.language.vhdl.Ports;

import net.mlanoe.language.vhdl.declaration.Declaration;

import net.mlanoe.language.vhdl.expression.Expression;

import net.mlanoe.language.vhdl.statement.Statement;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link net.mlanoe.language.vhdl.statement.BlockStatement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BlockStatementValidator {
	boolean validate();

	boolean validateGuard(Expression value);
	boolean validateGeneric(Generics value);
	boolean validateGenericMap(GenericMaps value);
	boolean validatePort(Ports value);
	boolean validatePortMap(PortMaps value);
	boolean validateDeclaration(EList<Declaration> value);
	boolean validateStatement(EList<Statement> value);
}
