/*
 * generated by Xtext
 */
package net.mlanoe.language.vhdl.xtext.ui.contentassist

import net.mlanoe.language.vhdl.xtext.ui.contentassist.AbstractVhdlProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class VhdlProposalProvider extends AbstractVhdlProposalProvider {
}
